config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'
  resources :questions, only: [:index, :show, :new, :create, :edit, :update] do
    resources :answers, only: [:index, :create]
  end  

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :description, presence: true
  validates :description, length: { minimum: 50 }
  belongs_to :question
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, presence: true
  validates :title, length: { minimum:20 }
  validates :description, length: { minimum:50 }
  validates :description, presence: true
  has_many :answers
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
  def show
    @answer = Answer.find(params[:answer_id])
    @answer = Answer.new
  end
  
  def new
    @answer = Answer.all
  end

  def create 
    # binding.pry
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @answers = @question.answers
    @answer.question = @question 

    if @answer.save
      redirect_to @question
    else
      render :'questions/show'
    end
  end
  
  private 

  def answer_params
    params.require("answer").permit(:description)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
   @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers 
    @answer = Answer.new
  end

  def new
    @question = Question.new
  end
  
  def create 
    @question = Question.new(question_params)

    if @question.save
      redirect_to @question
    else
      render:new
    end
  end

  private

  def question_params
    params.require("question").permit(:title, :description)
  end
end

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueMission</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <nav class="top-bar">
    <h1><a href="/">RescueMission</a></h1>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  
  <%- if Rails.env.development? || Rails.env.test? -%> 
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>
  
  <%= yield :extra_footer %>
</body>
</html>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.title %></td>
        <td><% question.created_at.strftime("Posted on %B %d %Y") %></td>
        <td><%= link_to 'Show', question %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Question', new_question_path %>

app/views/questions/new.html.erb
<%= form_for(@question) do |f| %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @question.title %>
  </br>
  <strong>Answer:</strong>
  <%= @question.description %>
</p>
    <% if @question.answers%>
    <% @answers.each do |answer| %>
      <tr>
      <td><%= answer.description %></td>
      </tr>
    <% end %>
    <% end %>



<%= form_for [@question, @answer] do |f| %>
    <%= f.label :description %><br />
    <%= f.text_field :description %>

    <%= f.submit %>
<% end %>

<%= link_to 'Back', questions_path %>